# Generated by Django 3.0.3 on 2021-03-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=500)),
                ('select_Date', models.DateField()),
                ('select_Department', models.CharField(max_length=50)),
                ('Phone_Number', models.IntegerField()),
                ('Additional_Message', models.TextField()),
            ],
        ),
    ]
